theme: jekyll-theme-cayman
title: GO Getter Summer 2020 Course - Final Projects
description: A showcase of final projects covering educational equity and school segregation.
github:
  is_project_page: false
